baseURL = "https://adonyth.github.io/"
title = "AI Tools Radar"
theme = "PaperMod"
relativeURLs = false
canonifyURLs = true

[author]
name = "Adonyth"

[params]
author = "Adonyth"
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableThemeToggle = false
